spring:
  application:
    name: ps-everyday
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${ps.db.endpoint}/${ps.db.dbname}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com


boj:
  page:
    start: 1
    end: 320
